### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by brimwats1** [YunoHost-Apps/beehive_ynh#2]
I tried installing today on a whim, and here are the error logs: https://paste.yunohost.org/raw/ozociletur

**Comment by anmol26s** [comment]
I have updated it. 
Can you test it again for testing branch?
`$ yunohost app install --debug https://github.com/YunoHost-Apps/beehive_ynh/tree/testing`

**Comment by brimwats1** [comment]
Thanks! Install was successful. I can try testing it out tomorrow
